# https://github.com/VictorGabriel7Dev/telegram-antispam-bot
# https://victorgabriel.dev/projetos/telegram-antispam-bot
# SPDX-License-Identifier: AGPL-3.0-or-later
# Vesion: 1.04
#
# Author: Victor Gabriel https://victorgabriel.dev
# E-mail: contato@victorgabriel.dev
# GitHub: https://github.com/VictorGabriel7Dev
# Discord: @VictorGabriel.dev
# Telegram: https://t.me/VictorGabriel_Dev
# Generated by: Claude https://claude.ai

from telethon import events, TelegramClient
from telethon.tl.functions.channels import EditBannedRequest
from telethon.tl.types import ChatBannedRights
import re, time, traceback

textos = {
	'bot_api': BOT_API,
	'bot_hash': "BOT_HASH",
	'bot_sessao': "/path/telegram.session",
	'bot_token': "BOT_TOKEN",
	'versao': "1.04"
}

client = TelegramClient(textos['bot_sessao'], textos['bot_api'], textos['bot_hash'])

regex1 = r'[O\u00A0-\u00FF\uFF9E-\uFFDF\u0021-\u002F\u003A-\u0040\u005B-\u0060\u007B-\u007E\u2000-\u206F\u20D0-\u20FF\u2190-\u22FF\u2300-\u245F\u2460-\u27FF\u2800-\u297F\u2B00-\u2BFF\u2B1B-\u2B1C\u2B50\u2B55\u2E00-\u2EFF\u2F00-\u2FFF\u3000-\u303F\u31A0-\u31EF\u3400-\u4DBF\u4E00-\u9FFF\uA700-\uA7FF\uE000-\uF8FF\uF900-\uFAFF\uFE00-\uFEFF\uFF01-\uFF9D\uFFE0-\uFFEE\uFFF0-\uFFFF\U0001F000-\U0001FAFF\U00020000-\U00034FAF]+@\w{5,32}(?:[O\u00A0-\u00FF\uFF9E-\uFFDF\u0021-\u002F\u003A-\u0040\u005B-\u0060\u007B-\u007E\u2000-\u206F\u20D0-\u20FF\u2190-\u22FF\u2300-\u245F\u2460-\u27FF\u2800-\u297F\u2B00-\u2BFF\u2B1B-\u2B1C\u2B50\u2B55\u2E00-\u2EFF\u2F00-\u2FFF\u3000-\u303F\u31A0-\u31EF\u3400-\u4DBF\u4E00-\u9FFF\uA700-\uA7FF\uE000-\uF8FF\uF900-\uFAFF\uFE00-\uFEFF\uFF01-\uFF9D\uFFE0-\uFFEE\uFFF0-\uFFFF\U0001F000-\U0001FAFF\U00020000-\U00034FAF]+)*'
regex2 = r'[\u00A0-\u00FF\uFF9E-\uFFDF\u0021-\u002F\u003A-\u0040\u005B-\u0060\u007B-\u007E\u2000-\u206F\u20D0-\u20FF\u2190-\u22FF\u2300-\u245F\u2460-\u27FF\u2800-\u297F\u2B00-\u2BFF\u2B1B-\u2B1C\u2B50\u2B55\u2E00-\u2EFF\u2F00-\u2FFF\u3000-\u303F\u31A0-\u31EF\u3400-\u4DBF\u4E00-\u9FFF\uA700-\uA7FF\uE000-\uF8FF\uF900-\uFAFF\uFE00-\uFEFF\uFF01-\uFF9D\uFFE0-\uFFEE\uFFF0-\uFFFF\U0001F000-\U0001FAFF\U00020000-\U00034FAF]{3}'
regex3 = r'[\u00A0-\u00FF\uFF9E-\uFFDF\u0021-\u002F\u003A-\u0040\u005B-\u0060\u007B-\u007E\u2000-\u206F\u20D0-\u20FF\u2190-\u22FF\u2300-\u245F\u2460-\u27FF\u2800-\u297F\u2B00-\u2BFF\u2B1B-\u2B1C\u2B50\u2B55\u2E00-\u2EFF\u2F00-\u2FFF\u3000-\u303F\u31A0-\u31EF\u3400-\u4DBF\u4E00-\u9FFF\uA700-\uA7FF\uE000-\uF8FF\uF900-\uFAFF\uFE00-\uFEFF\uFF01-\uFF9D\uFFE0-\uFFEE\uFFF0-\uFFFF\U0001F000-\U0001FAFF\U00020000-\U00034FAF]+'
regex4 = r'[@\w]'


@client.on(events.NewMessage)
async def handler_newmessage(event):
	if event.message and event.message.message and (
		(
			not getattr(event, "fwd_from", None)
			and not getattr(event, "via_bot_id", None)
			and not getattr(event, "via_business_bot_id", None)
			and not getattr(event, "reply_to", None)
			and not getattr(event, "media", None)
			and not getattr(event, "reply_markup", None)
			and not getattr(event, "forwards", None)
			and not getattr(event, "post_author", None)
			and not getattr(event, "grouped_id", None)
			and re.fullmatch(regex1, re.sub(r'[0-9\s]+', '', event.message.message))
		) or (
			event.message.reply_to
			and not getattr(event.message, 'fwd_from', None)
			and not getattr(event.message, 'grouped_id', None)
			and not getattr(event.message.reply_to, 'reply_to_top_id', None)
			and getattr(event.message.reply_to, 'quote_text', None)
			and getattr(event.message.reply_to, 'reply_from', None)
			and getattr(event.message.reply_to, 'reply_to_peer_id', None)
			and getattr(event.message.reply_to.reply_from, 'from_id', None)
			and event.message.reply_to.reply_from.from_id != event.message.peer_id
			and event.message.reply_to.reply_to_peer_id != event.message.peer_id
			and re.search(regex2, re.sub(r'[\s\n\rA-Za-z0-9]+', '', event.message.reply_to.quote_text))
			and re.fullmatch(regex3, re.sub(r'[\s\n\rA-Za-z0-9]+', '', event.message.message))
		)
	):
		try:
			await event.delete()
		except Exception:
			pass
		try:
			await event.client(EditBannedRequest(
				event.peer_id,
				event.from_id,
				ChatBannedRights(until_date=None, view_messages=True)
			))
		except Exception:
			pass


async def main():
	await client.start(bot_token=textos['bot_token'])
	await client.run_until_disconnected()


while True:
	try:
		with client:
			client.loop.run_until_complete(main())
	except Exception as erro:
		print("\n\n-------------\n\nError:", erro)
		traceback.print_exc()
		time.sleep(5)
